/**
 * GENERATED by scripts/generate-golden-module-files.ts — do not edit by hand.
 *
 * Which files each lockable module protects. 43 of 58 modules
 * resolve to at least one file; the rest are catalog entries with no source of
 * their own yet, and the UI shows their file count so a lock never implies
 * protection it does not have.
 *
 * Regenerate after adding a module or moving its implementation:
 *   npx tsx scripts/generate-golden-module-files.ts
 */
import type { LockableEntity } from "./ownerLockRegistry";

export const GENERATED_LOCKABLE_MODULES: readonly LockableEntity[] = [
  {
    "id": "channel-inception-research",
    "label": "Channel Research Evidence",
    "kind": "module",
    "description": "inception/research · Channel Inception contract 1.0.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-positioning",
    "label": "Positioning, Style DNA & Show Bible",
    "kind": "module",
    "description": "inception/identity · Channel Inception contract 1.1.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-seo",
    "label": "SEO & Editorial Foundation",
    "kind": "module",
    "description": "inception/editorial · Channel Inception contract 1.0.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-voice",
    "label": "Voice Casting & Readiness",
    "kind": "module",
    "description": "inception/voice · Channel Inception contract 1.0.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-avatar",
    "label": "Channel Avatar",
    "kind": "module",
    "description": "inception/brand · Channel Inception contract 1.1.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-banner",
    "label": "Banner, Background & Color System",
    "kind": "module",
    "description": "inception/brand · Channel Inception contract 1.0.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-thumbnails",
    "label": "Thumbnail Foundation & Starter Slate",
    "kind": "module",
    "description": "inception/package · Channel Inception contract 1.0.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-pipeline",
    "label": "Family Pipeline Compile",
    "kind": "module",
    "description": "inception/pipeline · Channel Inception contract 1.0.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-probe",
    "label": "Bounded Family Probe",
    "kind": "module",
    "description": "inception/probe · Channel Inception contract 1.0.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "channel-inception-readiness",
    "label": "Channel Tile & Readiness Projection",
    "kind": "module",
    "description": "inception/project · Channel Inception contract 1.0.0 (catalog-only; no executor bound)",
    "paths": []
  },
  {
    "id": "episode-graph",
    "label": "Episode Graph — Causal Scene Plan",
    "kind": "module",
    "description": "brief · Typed Story Spine bridge → provider-free Episode Graph + deterministic Scene Manifest",
    "paths": [
      "src/engine/__tests__/factualReviewBoundary.test.ts",
      "src/engine/episodeGraph.ts",
      "src/trigger/blocks/episodeGraphBlocks.ts"
    ]
  },
  {
    "id": "self-contained-story",
    "label": "Self-Contained Story — Sealed Renderer Handoff",
    "kind": "module",
    "description": "brief · Provider-free approved native plan → route, lane, program-brief, and topic-bound immutable renderer receipt",
    "paths": [
      "src/trigger/blocks/selfContainedStoryBlocks.ts"
    ]
  },
  {
    "id": "casefile-documentary",
    "label": "Casefile Documentary — Source-First Evidence Grammar",
    "kind": "module",
    "description": "brief · Provider-independent Case Packet → primary-source / rights / editorial-admission receipt → cited evidence grammar",
    "paths": [
      "src/trigger/blocks/casefileSourcePacketBlocks.ts"
    ]
  },
  {
    "id": "casefile-evidence-shot-map",
    "label": "Casefile Evidence Shot Map — Claim-to-Visual Review",
    "kind": "module",
    "description": "brief · Provider-free admitted Casefile Source Packet + current Scene Manifest + current Story Spine ShotPlan → reviewer-signed factual claim map",
    "paths": [
      "src/trigger/blocks/casefileEvidenceShotMapBlocks.ts"
    ]
  },
  {
    "id": "source-bound-story-spine",
    "label": "Source-Bound Story Spine — Timed Evidence Handoff",
    "kind": "module",
    "description": "brief · Provider-free admitted Casefile source packet + reviewed evidence-shot map + current timed Story Spine → exact claim/source/citation/treatment handoff",
    "paths": [
      "src/trigger/blocks/sourceBoundStorySpineBlocks.ts"
    ]
  },
  {
    "id": "editorial-evidence-packet",
    "label": "Editorial Evidence Packet — Shared Factual Core",
    "kind": "module",
    "description": "brief · Provider-free reviewed sources + approved claims + immutable snapshot hashes → factual-visual source binding",
    "paths": [
      "src/trigger/blocks/editorialEvidencePacketBlocks.ts"
    ]
  },
  {
    "id": "cinematic-case-sequence",
    "label": "Cinematic Case Sequence — Evidence-Led Multi-Shot Direction",
    "kind": "module",
    "description": "brief · Admitted Casefile evidence map + Story Spine → reviewer-signed causal coverage units → exact Novita scene plan / EDL / visual-review locks",
    "paths": [
      "src/trigger/blocks/cinematicCaseSequenceBlocks.ts"
    ]
  },
  {
    "id": "learning-contract",
    "label": "Learning Contract — Objective to Retrieval Practice",
    "kind": "module",
    "description": "brief · Episode Graph → typed objective, source-linked demonstration, recap, retrieval-practice, and human-review handoff",
    "paths": [
      "src/engine/learningContract.ts",
      "src/trigger/blocks/learningContractBlocks.ts"
    ]
  },
  {
    "id": "children-show-bible",
    "label": "Children’s Show Bible — Curriculum, Identity, and Participation",
    "kind": "module",
    "description": "brief · Operator-authored age band + one measurable objective + original recurring world/character identity + five-stage child-participation admission",
    "paths": [
      "src/trigger/blocks/childrenShowBibleBlocks.ts",
      "src/trigger/blocks/curriculumEpisodeSeedBlocks.ts"
    ]
  },
  {
    "id": "scene-compiler",
    "label": "Scene Compiler — Deterministic Illustration",
    "kind": "module",
    "description": "visual · Episode Graph Scene Manifest → local Remotion + FFmpeg master (zero remote media calls)",
    "paths": [
      "src/engine/__tests__/factualReviewBoundary.test.ts",
      "src/trigger/blocks/sceneCompilerBlocks.ts",
      "src/trigger/blocks/syntheticScenarioBlocks.ts"
    ]
  },
  {
    "id": "child-content-safety",
    "label": "Children’s Learning Safety — Human Review Receipt",
    "kind": "module",
    "description": "verify · Deterministic audience, language, curriculum, and release-mode admission gate",
    "paths": [
      "src/trigger/blocks/childrenSafetyBlocks.ts"
    ]
  },
  {
    "id": "loreshort",
    "label": "Lore Short — Loreshort Engine",
    "kind": "module",
    "description": "visual · Loreshort — Gemini first-person lore script + attested Novita stills + per-line cast-voice TTS + attested Novita LTX image-to-video depth camera moves + FREE ffmpeg 2K finish",
    "paths": [
      "src/engine/blocks.ts",
      "src/lib/loreshort.ts",
      "src/trigger/blocks/loreShortBlocks.ts"
    ]
  },
  {
    "id": "novita-render-farm",
    "label": "Novita Render Farm",
    "kind": "module",
    "description": "visual · Direct Trigger-controlled Novita RTX 4090 spot workers — Z-Image keyframes followed by sealed LTX-2.5 image-to-video, one exact shot job per worker, durable R2 manifests, and verified worker teardown",
    "paths": [
      "src/trigger/blocks/novitaRenderBlocks.ts"
    ]
  },
  {
    "id": "imagecraft-novita",
    "label": "Imagecraft (Novita Z-Image)",
    "kind": "module",
    "description": "visual · Imagecraft — direct Novita Z-Image Turbo BF16 reference stills on RTX 4090 spot workers, with profile-bound 1280×736, 1920×1088, or 2048×1152 output, R2 provenance, and verified autoclose",
    "paths": []
  },
  {
    "id": "videocraft-novita",
    "label": "Videocraft (Novita LTX-2.5 x2)",
    "kind": "module",
    "description": "visual · Videocraft — LTX-2.5 distilled image-to-video on an exact RTX 4090 spot profile: 640×352 stage one → native latent-space x2 refinement → 1280×704 final output, FP8-cast + CPU offload, with no model or hardware fallback.",
    "paths": []
  },
  {
    "id": "lofi",
    "label": "Lofi Loop — Novita Ambient Engine",
    "kind": "module",
    "description": "visual · A Style-DNA-locked Novita Z-Image Turbo still, independently reviewed by a non-Google vision provider, is the exact source frame for a certified Novita LTX-2.5 image-to-video loop. A bounded seam treatment, mastered music mix, and final visual evidence turn it into an ambient product.",
    "paths": [
      "src/engine/__tests__/stageBudget.test.ts",
      "src/trigger/blocks/lofiBlocks.ts"
    ]
  },
  {
    "id": "quiz",
    "label": "Quiz — Quizcraft (NOT BUILDABLE under current licensing — design reference only)",
    "kind": "module",
    "description": "visual · No implementation exists. This entry documents a design intent — trivia / flag-guess / music-guess → a deterministic dataset-backed answer → an isolated Remotion composition — that three independent audit passes (2026-08) each found unbuildable as specified. Nothing in this entry is wired: no executableIds, no family, no content lane. `public/golden/quiz/*.{jpg,mp4}` are early visual-format proofs only, not evidence the pipeline can produce this content lawfully or repeatably.",
    "paths": []
  },
  {
    "id": "quiz-year",
    "label": "Quiz — Guess the Year (Wikidata)",
    "kind": "module",
    "description": "visual · quiz_year — CC0 Wikidata facts → four-option rounds → isolated Remotion bundle (src/lib/quizYearFacts.ts, src/trigger/blocks/quizYearBlocks.ts:341's quiz_year block, src/remotion/quiz/Root.tsx, src/lib/quizYearRender.ts)",
    "paths": [
      "src/trigger/blocks/quizPlanningBlocks.ts",
      "src/trigger/blocks/quizYearBlocks.ts"
    ]
  },
  {
    "id": "quiz-short-private-release",
    "label": "QuizShort — Registered Private-Release Block (No Owner Intake)",
    "kind": "module",
    "description": "ship · quiz_short_release — certified QuizYear fact/source receipts + final visual/audio QA + opening evidence → private human-review receipt",
    "paths": [
      "src/trigger/blocks/quizShortReleaseBlocks.ts"
    ]
  },
  {
    "id": "thumbnail",
    "label": "Thumbnail — Banana Engine",
    "kind": "module",
    "description": "package · Text-free Flash scene + deterministic Style-DNA typography",
    "paths": [
      "src/engine/__tests__/healerPolicy.test.ts",
      "src/engine/__tests__/recoveryPolicy.test.ts",
      "src/lib/banana.ts",
      "src/lib/falNanoBananaProThumbnail.ts",
      "src/lib/falNanoBananaProThumbnailContract.ts",
      "src/lib/nanoBananaThumbnailContract.ts",
      "src/lib/thumbnailCapabilities.ts",
      "src/lib/thumbnailChannelIdentity.ts",
      "src/lib/thumbnailCtrFeedback.ts",
      "src/lib/thumbnailDefaults.ts",
      "src/lib/thumbnailDefectLedger.ts",
      "src/lib/thumbnailGoldenStandard.ts",
      "src/lib/thumbnailLab.ts",
      "src/lib/thumbnailLayout.ts",
      "src/lib/thumbnailLearningStore.ts",
      "src/lib/thumbnailMobileGate.ts",
      "src/lib/thumbnailOcr.ts",
      "src/lib/thumbnailPaletteGuard.ts",
      "src/lib/thumbnailPanelDetector.ts",
      "src/lib/thumbnailRenderTier.ts",
      "src/lib/thumbnailRenderer.ts",
      "src/lib/thumbnailSafeZone.ts",
      "src/lib/thumbnailSameness.ts",
      "src/lib/thumbnailStoryInterest.ts",
      "src/lib/thumbnailStoryJudge.ts",
      "src/trigger/blocks/intelligenceBlocks.ts"
    ]
  },
  {
    "id": "package-opening-proof",
    "label": "Package → Opening Evidence",
    "kind": "module",
    "description": "package · Typed package plan → exact cover bytes → reviewed opening/master receipt",
    "paths": [
      "src/trigger/blocks/intelligenceBlocks.ts"
    ]
  },
  {
    "id": "topic-intel",
    "label": "Topic Intel — Topicraft",
    "kind": "module",
    "description": "intel · Topicraft — evidence-cited topic BETS (outlier bank + Reddit + autocomplete + competitor gaps), judge-gated portfolio",
    "paths": [
      "src/lib/__tests__/pipelineInvocationSnapshot.test.ts",
      "src/trigger/blocks/intelligenceBlocks.ts",
      "src/trigger/blocks/lofiBlocks.ts"
    ]
  },
  {
    "id": "serialized-program-episode-context",
    "label": "Serialized Episode Context — Immutable Continuity Receipt",
    "kind": "module",
    "description": "intel · Provider-free completed episode row → bounded route/run/topic-bound continuity projection",
    "paths": [
      "src/trigger/blocks/serializedProgramEpisodeContextBlocks.ts"
    ]
  },
  {
    "id": "narrative-series-visual-controls",
    "label": "Narrative Series Visual Controls — Sealed Shot Continuity",
    "kind": "module",
    "description": "brief · Provider-free Series Plan + Episode Graph/Story Spine + accepted character-adapter receipt → per-shot continuity contract",
    "paths": []
  },
  {
    "id": "show-bible",
    "label": "Show Bible + Crew",
    "kind": "module",
    "description": "brief · Standalone Crew module — crew as DATA: a declarative role registry (director / cinematographer / editor / composer / critic) + a pure resolveCrew over the channel's Show Bible (authored doctrines) + a CustomizationSurface (role toggles + 6 style presets). Critic authors the ValidationSpec the verify stage enforces",
    "paths": [
      "src/trigger/blocks/crewBlocks.ts",
      "src/trigger/blocks/storySpineBlocks.ts"
    ]
  },
  {
    "id": "script",
    "label": "Script + Hook",
    "kind": "module",
    "description": "write · Hookcraft cold-open engine + latest Gemini Pro narration (gemini-3.1-pro-preview)",
    "paths": [
      "src/trigger/blocks/narratedBlocks.ts"
    ]
  },
  {
    "id": "guard",
    "label": "Guard Gates",
    "kind": "module",
    "description": "guard · qa_script + originality_gate + compliance_check",
    "paths": [
      "src/engine/__tests__/factualReviewBoundary.test.ts",
      "src/trigger/blocks/complianceBlocks.ts",
      "src/trigger/blocks/narratedBlocks.ts"
    ]
  },
  {
    "id": "narration",
    "label": "Narration — Voicecraft",
    "kind": "module",
    "description": "voice · Voicecraft — profiled voice bank + archetype casting law + narration physics + audio-judged cold open (ElevenLabs v3 / Fish)",
    "paths": [
      "src/engine/__tests__/factualReviewBoundary.test.ts",
      "src/trigger/blocks/narratedBlocks.ts"
    ]
  },
  {
    "id": "music",
    "label": "Music — Scorecraft",
    "kind": "module",
    "description": "sound · Channel-scoped multi-track score with bounded provider routing and exact usage accounting",
    "paths": [
      "src/trigger/blocks/lofiBlocks.ts"
    ]
  },
  {
    "id": "visuals",
    "label": "Visuals",
    "kind": "module",
    "description": "visual · Family-swapped: FOOTAGECRAFT standalone stock engine (federated Pexels + Pixabay, 4K-ONLY, concurrent) / entity imagery / flux keyframes / boomerang loops",
    "paths": [
      "src/engine/__tests__/healerPolicy.test.ts",
      "src/lib/__tests__/finalMasterVisualReviewAlignment.test.ts",
      "src/lib/footagecraft.ts",
      "src/trigger/blocks/genFootageBlocks.ts",
      "src/trigger/blocks/narratedBlocks.ts",
      "src/trigger/blocks/novitaRenderBlocks.ts",
      "src/trigger/blocks/studioAssetLibraryBlocks.ts",
      "src/trigger/blocks/studioReusableMediaBlocks.ts",
      "src/trigger/blocks/visualMatterBlocks.ts"
    ]
  },
  {
    "id": "studio-assets",
    "label": "Studio Asset Library",
    "kind": "module",
    "description": "visual · Owner-scoped reusable camera, motion, prompt, presentation, character-adapter, and control-guide records",
    "paths": []
  },
  {
    "id": "cinematic",
    "label": "Cinematic — Cinecraft",
    "kind": "module",
    "description": "visual · Cinecraft — generated character/location-consistent cinematic shots (Nano Banana hero-anchor + Higgsfield Soul + Seedance/Kling i2v)",
    "paths": [
      "src/engine/visualMatter.ts",
      "src/lib/cinecraft.ts",
      "src/lib/crew/cinematographer.ts",
      "src/trigger/blocks/novitaRenderBlocks.ts",
      "src/trigger/blocks/visualMatterBlocks.ts"
    ]
  },
  {
    "id": "documotion",
    "label": "Documentary — Documotion",
    "kind": "module",
    "description": "visual · Documotion — themeable documentary-collage motion engine (Remotion + Banana stills & typography + real OSM geo, narration-first planner, vision still-verifier)",
    "paths": [
      "src/lib/documotion.ts",
      "src/trigger/blocks/documentaryCollageShortBlocks.ts"
    ]
  },
  {
    "id": "motioncraft",
    "label": "Motion Graphics — Motioncraft",
    "kind": "module",
    "description": "layer · Motioncraft — an LLM reads the script, decides which beats earn a motion graphic, picks the best free tool per beat, and renders each (MapLibre · Remotion · Nano Banana · p5.js)",
    "paths": [
      "src/lib/geoMap.ts",
      "src/lib/motioncraft.ts",
      "src/trigger/blocks/insertBlocks.ts"
    ]
  },
  {
    "id": "speech-tv",
    "label": "Motivation Speech — Speechcraft",
    "kind": "module",
    "description": "visual · Speechcraft — real public speeches → word-level transcript → best-segment plan → a self-contained Remotion vintage-broadcast composition (VintageFilter grain/scanlines/desaturation + KaraokeCaptions word-sync + ChannelBug segment marker + MotionCues), with a letterboxed CinematicSpeech variant, cloud-rendered",
    "paths": [
      "src/lib/remotionRender.ts"
    ]
  },
  {
    "id": "inserts",
    "label": "Data-Viz Inserts",
    "kind": "module",
    "description": "layer · Remotion motion graphics (visual_inserts)",
    "paths": [
      "src/trigger/blocks/insertBlocks.ts"
    ]
  },
  {
    "id": "layer",
    "label": "Captions + Presentation",
    "kind": "module",
    "description": "layer · Word-level captions, quote overlays, intro card, and approved Studio presentation recipes (Remotion/FFmpeg)",
    "paths": [
      "src/lib/assembly/module.ts",
      "src/trigger/blocks/narratedBlocks.ts",
      "src/trigger/blocks/studioAssetLibraryBlocks.ts"
    ]
  },
  {
    "id": "assemble",
    "label": "Assembly — EDL Engine",
    "kind": "module",
    "description": "build · Standalone Assembly module — a typed Timeline/EDL (planTimeline, the brain) rendered deterministically (renderTimeline over the ffmpeg primitives, the hands), per-account via a CustomizationSurface (10 knobs · 6 style presets), idempotent + heal-aware",
    "paths": [
      "src/engine/__tests__/healerPolicy.test.ts",
      "src/lib/__tests__/finalMasterVisualReviewAlignment.test.ts",
      "src/trigger/blocks/narratedBlocks.ts"
    ]
  },
  {
    "id": "metadata",
    "label": "SEO Metadata",
    "kind": "module",
    "description": "package · Metacraft — autocomplete-grounded candidates (latest Gemini Pro) + claims lint + feed judge",
    "paths": [
      "src/trigger/blocks/intelligenceBlocks.ts"
    ]
  },
  {
    "id": "verify",
    "label": "Artifact + Shot Gates",
    "kind": "module",
    "description": "verify · qa_assets + qa_shots + short_scene_qa + length_check",
    "paths": [
      "src/trigger/blocks/documentaryCollageShortBlocks.ts",
      "src/trigger/blocks/narratedBlocks.ts",
      "src/trigger/blocks/novitaRenderBlocks.ts"
    ]
  },
  {
    "id": "final-master-story-coverage",
    "label": "Final Master — Visual Quality + Narrated Story Coverage",
    "kind": "module",
    "description": "verify · qa_visual → full final-master transcript audit → content-addressed Story Spine coverage sidecar",
    "paths": [
      "src/engine/__tests__/cinematicFinalMasterQaAdmission.test.ts",
      "src/engine/__tests__/healerPolicy.test.ts",
      "src/lib/__tests__/finalMasterVisualReviewAlignment.test.ts",
      "src/lib/__tests__/visualReview.test.ts",
      "src/trigger/blocks/narratedBlocks.ts"
    ]
  },
  {
    "id": "whiteboard",
    "label": "Whiteboard — Drawn Cinema (synced scribe)",
    "kind": "module",
    "description": "visual · whiteboardSync — route-sealed non-Google storyboard + bounded attested Novita still scenes + Fish narration, Whisper-aligned and drawn in time with the voice.",
    "paths": [
      "src/trigger/blocks/whiteboardScribeBlocks.ts"
    ]
  },
  {
    "id": "comic",
    "label": "Comic — Motion-Comic Page Engine",
    "kind": "module",
    "description": "visual · motionComic — route-sealed non-Google structured story → text-free attested panel art → ElevenLabs multi-voice → vision anchors/keep-clear regions → deterministic Python comic-page render.",
    "paths": [
      "src/engine/__tests__/healerPolicy.test.ts",
      "src/lib/__tests__/visualReview.test.ts",
      "src/lib/motionComic.ts",
      "src/trigger/blocks/motionComicBlocks.ts"
    ]
  },
  {
    "id": "ship",
    "label": "Ship",
    "kind": "module",
    "description": "ship · YouTube upload (PRIVATE-first) + Ayrshare crosspost + Telegram",
    "paths": [
      "src/lib/__tests__/pipelineInvocationSnapshot.test.ts",
      "src/lib/__tests__/publishRetrySchedule.test.ts",
      "src/trigger/blocks/bundleBlocks.ts",
      "src/trigger/blocks/growthBlocks.ts",
      "src/trigger/blocks/lofiBlocks.ts"
    ]
  },
  {
    "id": "channel-planner",
    "label": "Channel Planner",
    "kind": "module",
    "description": "plan · plan-week-ahead Trigger task → contentPlan board (topic + thumbnail + description) + scheduled native-publish",
    "paths": [
      "src/trigger/planWeekAhead.ts"
    ]
  },
  {
    "id": "shorts",
    "label": "Shorts (vertical)",
    "kind": "module",
    "description": "visual · 9:16 short-form archetype (template D; families.ts visualEngine label \"shorts_cuts\" is a designer-internal switch, not a registered block) + long-form → Short repurposer (shorts_spinoff / documentary_short_candidates)",
    "paths": [
      "src/trigger/blocks/documentaryCollageShortBlocks.ts",
      "src/trigger/blocks/lofiBlocks.ts"
    ]
  },
  {
    "id": "publishing",
    "label": "Publishing + YouTube",
    "kind": "module",
    "description": "Upload, scheduling, thumbnail replacement and anything that reaches the live channel.",
    "paths": [
      "src/lib/youtube.ts",
      "src/lib/youtubeAnalytics.ts",
      "src/lib/youtubeThumbnailReplacement.ts",
      "src/lib/youtubeThumbnailReplacementRuntime.ts"
    ]
  },
  {
    "id": "vault",
    "label": "Credentials + vault",
    "kind": "module",
    "description": "Secret hydration and provider credential handling.",
    "paths": [
      "src/lib/storage.ts",
      "src/lib/vault.ts"
    ]
  }
];
