import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const planner = readFileSync(resolve(process.cwd(), "src/trigger/planWeekAhead.ts"), "utf8");
const script = readFileSync(resolve(process.cwd(), "src/trigger/planWeekPreparedScript.ts"), "utf8");
const narration = readFileSync(resolve(process.cwd(), "src/trigger/planWeekPreparedNarration.ts"), "utf8");
const music = readFileSync(resolve(process.cwd(), "src/trigger/planWeekPreparedMusic.ts"), "utf8");
const images = readFileSync(resolve(process.cwd(), "src/trigger/planWeekPreparedImages.ts"), "utf8");

assert.match(planner, /tasks\.trigger\("plan-week-prepared-script"/);
assert.match(planner, /idempotencyKeys\.create/);
assert.match(planner, /planWeekPreparationManifestSha256\(manifest\)/);
assert.match(planner, /PLAN_WEEK_PREPARED_SCRIPT_MAX_COST_USD/);
assert.match(script, /tasks\.trigger\("plan-week-prepared-narration"/);
assert.match(script, /idempotencyKeys\.create/);
assert.match(script, /PLAN_WEEK_PREPARED_NARRATION_MAX_COST_USD/);
assert.match(script, /retry: \{ maxAttempts: 2, minTimeoutInMs: 10_000, maxTimeoutInMs: 120_000, factor: 2 \}/);
assert.match(narration, /tasks\.trigger\("plan-week-prepared-music"/);
assert.match(narration, /idempotencyKeys\.create/);
assert.match(narration, /PLAN_WEEK_PREPARED_MUSIC_MAX_COST_USD/);
assert.match(narration, /retry: \{ maxAttempts: 2, minTimeoutInMs: 10_000, maxTimeoutInMs: 120_000, factor: 2 \}/);
assert.match(narration, /planStorySpine/);
assert.match(narration, /tasks\.trigger\("plan-week-prepared-images"/);
assert.match(narration, /idempotencyKeys\.create/);
assert.match(narration, /PLAN_WEEK_PREPARED_IMAGES_MAX_COST_USD/);
assert.match(music, /retry: \{ maxAttempts: 2, minTimeoutInMs: 10_000, maxTimeoutInMs: 120_000, factor: 2 \}/);
assert.match(images, /tasks\.trigger\("minimax-h3-weekly-batch"/);
assert.match(images, /planWeekPreparedH3FirstFrameKey/);
assert.match(images, /planWeekPreparedFootageClipKey/);
assert.match(images, /preparedFootage:/);
assert.match(images, /PLAN_WEEK_PREPARED_H3_MAX_COST_USD/);
assert.match(images, /retry: \{ maxAttempts: 2, minTimeoutInMs: 10_000, maxTimeoutInMs: 120_000, factor: 2 \}/);
console.log("automatic weekly prepared-media dispatch wiring passed");
