/**
 * Generates the file map an owner module lock protects.
 *
 * A lock that names the wrong files is worse than no lock: it reports
 * protection the guard does not provide. So the map is DERIVED, never guessed —
 * from three mechanical sources, unioned:
 *
 *   1. curated overrides, for modules whose blast radius was worked out by hand
 *      (the thumbnail module spans gates and learning loops that no automatic
 *      rule would associate with it)
 *   2. source paths the catalog entry names in its own prose ("Implemented by
 *      src/engine/episodeGraph.ts ...")
 *   3. every file declaring one of the module's executable block ids, found by
 *      scanning for the `id: "<blockId>"` literal
 *
 * Over-inclusion is the safe direction: an extra file makes a lock refuse a
 * little more than strictly necessary, while a missing file lets a worker edit
 * the thing the owner locked. Result is committed so it works on Vercel, where
 * no repository scan is possible at runtime.
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

import { GOLDEN_MODULES } from "@/engine/golden";
import { catalogExecutionBinding } from "@/engine/goldenExecution";

const ROOT = process.cwd();
const SKIP_DIRS = new Set(["node_modules", ".next", ".git", "dist", "build", ".locks"]);

/** Hand-worked blast radii that no automatic rule would reproduce. */
const CURATED: Record<string, readonly string[]> = {
  thumbnail: [
    "src/lib/thumbnailLab.ts",
    "src/lib/banana.ts",
    "src/lib/thumbnailStoryInterest.ts",
    "src/lib/thumbnailStoryJudge.ts",
    "src/lib/thumbnailCapabilities.ts",
    "src/lib/thumbnailChannelIdentity.ts",
    "src/lib/thumbnailGoldenStandard.ts",
    "src/lib/thumbnailMobileGate.ts",
    "src/lib/thumbnailPaletteGuard.ts",
    "src/lib/thumbnailPanelDetector.ts",
    "src/lib/thumbnailSameness.ts",
    "src/lib/thumbnailDefectLedger.ts",
    "src/lib/thumbnailCtrFeedback.ts",
    "src/lib/thumbnailLearningStore.ts",
    "src/lib/thumbnailDefaults.ts",
    "src/lib/thumbnailRenderTier.ts",
    "src/lib/thumbnailOcr.ts",
    "src/lib/thumbnailRenderer.ts",
    "src/lib/thumbnailLayout.ts",
    "src/lib/thumbnailSafeZone.ts",
    "src/lib/falNanoBananaProThumbnail.ts",
    "src/lib/falNanoBananaProThumbnailContract.ts",
    "src/lib/nanoBananaThumbnailContract.ts",
  ],
};

/** Lockable things that are not catalog modules but are worth freezing. */
const EXTRA_MODULES: { id: string; label: string; description: string; paths: string[] }[] = [
  {
    id: "publishing",
    label: "Publishing + YouTube",
    description: "Upload, scheduling, thumbnail replacement and anything that reaches the live channel.",
    paths: [
      "src/lib/youtube.ts",
      "src/lib/youtubeThumbnailReplacement.ts",
      "src/lib/youtubeThumbnailReplacementRuntime.ts",
      "src/lib/youtubeAnalytics.ts",
    ],
  },
  {
    id: "vault",
    label: "Credentials + vault",
    description: "Secret hydration and provider credential handling.",
    paths: ["src/lib/vault.ts", "src/lib/storage.ts"],
  },
];

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.tsx?$/.test(entry)) out.push(full);
  }
  return out;
}

function main(): void {
  const files = walk(join(ROOT, "src"));
  const contents = new Map<string, string>();
  for (const file of files) contents.set(relative(ROOT, file), readFileSync(file, "utf8"));

  const rows = GOLDEN_MODULES.map((module) => {
    const paths = new Set<string>(CURATED[module.key] ?? []);

    for (const match of module.how.matchAll(/\b(src\/[\w/.-]+\.tsx?)\b/g)) paths.add(match[1]);

    const binding = catalogExecutionBinding(module.key);
    const executableIds = "executableIds" in binding ? binding.executableIds : [];
    for (const blockId of executableIds) {
      const needle = `id: "${blockId}"`;
      for (const [path, text] of contents) {
        if (text.includes(needle)) paths.add(path);
      }
    }

    return {
      id: module.key,
      label: module.title,
      kind: "module" as const,
      description: `${module.stage} · ${module.engine}`,
      paths: [...paths].sort(),
    };
  });

  const all = [
    ...rows,
    ...EXTRA_MODULES.map((extra) => ({
      id: extra.id,
      label: extra.label,
      kind: "module" as const,
      description: extra.description,
      paths: [...extra.paths].sort(),
    })),
  ];

  const covered = all.filter((row) => row.paths.length > 0).length;
  const body = `/**
 * GENERATED by scripts/generate-golden-module-files.ts — do not edit by hand.
 *
 * Which files each lockable module protects. ${covered} of ${all.length} modules
 * resolve to at least one file; the rest are catalog entries with no source of
 * their own yet, and the UI shows their file count so a lock never implies
 * protection it does not have.
 *
 * Regenerate after adding a module or moving its implementation:
 *   npx tsx scripts/generate-golden-module-files.ts
 */
import type { LockableEntity } from "./ownerLockRegistry";

export const GENERATED_LOCKABLE_MODULES: readonly LockableEntity[] = ${JSON.stringify(all, null, 2)};
`;

  writeFileSync(join(ROOT, "src/lib/goldenModuleFiles.generated.ts"), body, "utf8");
  console.log(`generated ${all.length} lockable modules · ${covered} with at least one file`);
  for (const row of all) {
    if (row.paths.length === 0) console.log(`  no files derived: ${row.id}`);
  }
}

main();
