import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

async function main(): Promise<void> {
  const source = await readFile(join(process.cwd(), "src/app/(app)/studio-assets/page.tsx"), "utf8");
  const styles = await readFile(join(process.cwd(), "src/app/(app)/studio-assets/studio-assets.module.css"), "utf8");
  const api = await readFile(join(process.cwd(), "src/app/api/studio-assets/route.ts"), "utf8");
  assert.match(source, /Studio assets/i);
  assert.match(source, /function AssetHero/);
  assert.match(source, /Reuse what has earned the right\./);
  assert.match(source, /function AssetRoomTabs/);
  for (const room of ["approved", "decisions", "identity", "runtime", "catalog"]) {
    assert.match(source, new RegExp(`room === "${room}"`), `missing isolated ${room} room`);
  }
  assert.match(source, /function LockedAssetRegistry/);
  assert.match(source, /No private asset request was sent/);
  assert.match(source, /Registry locked/,
    "viewer mode must not imply that a private registry request is loading");
  assert.doesNotMatch(source, /<PageHeader/);
  assert.doesNotMatch(source, /<OwnerOnlyNotice/);
  assert.match(source, /Read-only evidence inventory/i);
  assert.match(source, /Reviewed candidates awaiting approval/i);
  assert.match(source, /Approve for this channel/i);
  assert.match(source, /rechecks its retained release evidence/i);
  assert.match(source, /Nothing becomes Studio-wide automatically/i);
  assert.match(source, /action: "approve-candidate"/);
  assert.match(source, /persistent signed URLs/);
  assert.match(source, /short-lived preview for an approved image/);
  assert.match(source, /Official LTX catalog/i);
  assert.match(source, /Visual treatment catalog/i);
  assert.match(source, /no renderer admitted/i);
  assert.match(source, /Future supervised route seeds/i);
  assert.match(source, /not installed/i);
  assert.match(source, /Official workflow family/i);
  assert.match(source, /still requires a pinned local graph and benchmark/i);
  assert.match(source, /adapter pin · licence · direct benchmark/i);
  assert.match(source, /adapter pin · licence · workflow · guide · benchmark/i);
  assert.match(source, /assembly consumer is not admitted until render-parity is proven/i);
  assert.match(source, /fetch\("\/api\/studio-assets"/);
  assert.match(source, /Preview approved image/);
  assert.match(source, /api\/studio-assets\?preview=/);
  assert.match(source, /Approved source asset/);
  assert.match(source, /document\.addEventListener\("keydown", onKeyDown\)/);
  assert.match(source, /event\.key === "Escape"/);
  assert.match(source, /previewOriginRef\.current\?\.focus\(\)/);
  assert.match(source, /event\.key === "Tab"/);
  assert.doesNotMatch(source, /r2Key/);
  assert.match(source, /direct LTX blocked/i);
  assert.match(source, /Dedicated ComfyUI\/LTX/i);
  assert.match(source, /RTX 5090/i);
  assert.match(source, /Self-hosted open-weight LTX 2\.5 candidate/);
  assert.match(source, /our own Studio library, not an external LTX service/i);
  assert.match(source, /Persistent character adapters/i);
  assert.match(source, /acceptedCharacterLoRAs/);
  assert.match(source, /accepted for reuse/i);
  assert.doesNotMatch(source, /adapterReference/);
  assert.match(source, /musicVideoA2Vid\.label/);
  assert.match(source, /benchmark admitted/i);
  assert.match(source, /Dispatch remains disabled/i);
  assert.match(source, /no external LTX service/i);
  assert.match(source, /No render permission yet/i);
  assert.match(source, /Direct LTX runtime/i);
  assert.match(source, /benchmark not admitted/i);
  assert.match(source, /owner-scoped benchmark admission/i);
  assert.match(source, /32 GB VRAM/i);
  assert.match(source, /executionTarget/);
  assert.match(source, /Final-master signal/i);
  assert.match(source, /demonstrated tie-break evidence/i);
  assert.match(source, /approval and benchmark remain the only selection evidence/i);
  assert.match(source, /qualityMetric/);
  assert.match(source, /qualityPhase/);
  assert.doesNotMatch(source, /asset\.resource\.r2Key/);
  assert.match(api, /requireStudioActor/);
  assert.match(api, /resolveStudioAssetApprovedImagePreview/);
  assert.match(api, /presignDownload\(preview\.r2Key, \{ expiresIn: 300 \}\)/);
  assert.match(api, /Cache-Control": "private, no-store/);
  assert.doesNotMatch(api, /r2Key:\s*preview/);
  assert.match(api, /listStudioAssetLibraryInventory/);
  assert.match(api, /listStudioAssetPromotionCandidates/);
  assert.match(api, /getStudioAssetPromotionCandidateForApproval/);
  assert.match(api, /approveStudioAssetPromotionCandidateForOwner/);
  assert.match(api, /verifyFinalMasterReleaseEvidenceObjects/);
  assert.match(api, /export async function POST/);
  assert.match(api, /action !== "approve-candidate"/);
  assert.match(api, /candidate\.origin\.finalMasterReleaseCertificateKey/);
  assert.match(api, /certificate\.finalMaster\.sha256 !== candidate\.origin\.finalMasterSha256/);
  assert.doesNotMatch(api, /recipe:\s*body/);
  assert.match(api, /listStudioAssetReleaseFeedback/);
  assert.match(api, /listAcceptedCharacterLoRAInventory/);
  assert.match(api, /acceptedCharacterLoRAs/);
  assert.match(api, /selfHostedMusicVideoA2VidStudioReadiness/);
  assert.match(api, /listActiveMusicVideoA2VidRuntimeAdmissions/);
  assert.match(api, /musicVideoA2Vid/);
  assert.match(api, /resolveOwnerReviewedLtxRuntime/);
  assert.match(api, /directLtxRuntime/);
  assert.match(api, /benchmarkedProfileCount/);
  assert.doesNotMatch(api, /admissionFingerprints/);
  assert.match(api, /releaseFeedback/);
  assert.match(api, /studioCuratedLtxCatalog/);
  assert.match(api, /OFFICIAL_LTX_COMFY_IC_LORA_WORKFLOW_PROFILES/);
  assert.match(api, /COMFY_IC_LORA_REQUIRED_GPU_SKU/);
  assert.match(api, /COMFY_IC_LORA_MINIMUM_VRAM_GB/);
  assert.match(api, /executionTarget/);
  assert.match(api, /recommendedWorkflowProfiles/);
  assert.match(api, /VISUAL_TREATMENT_CATALOG/);
  assert.match(api, /activePlanningFamilies/);
  assert.match(styles, /\.orbitField/);
  assert.match(styles, /prefers-reduced-motion: reduce/);
  console.log("studio assets UI contracts passed");
}

void main();
