import assert from 'node:assert/strict';
import { sourceCitationOccurs } from '../sourceCitation';

const cases: [string, string, boolean][] = [
  ['Source: IMF', 'According to the IMF, output rose by two percent.', true],
  ['Source: World Bank', 'The world of bankers reported two percent.', false],
  ['Source: Federal Reserve', 'According to the Federal Reserve, rates rose.', true],
  ['Source: World Bank', 'According to the Federal Reserve, rates rose.', false],
  ['Source: UN', 'According to the U.N., the number increased.', true],
  ['Source: UN', 'The number increased unexpectedly.', false],
  ['Source: U.S. Bureau of Labor Statistics', 'According to the US Bureau of Labor Statistics, wages rose.', true],
  ['Source: G7', 'According to the G7, investment increased.', true],
  ['Source: G7', 'According to G70 researchers, investment increased.', false],
  ['Source: S&P Global', 'Data from S and P Global show a change.', true],
  ['Source: Bank of England', 'According to the Bank of England, rates rose.', true],
  ['Source: Bank England', 'According to the Bank of England, rates rose.', false],
  ['Source: Federal Reserve, 2023', 'According to a 2023 analysis by the Federal Reserve, rates rose.', true],
  ['Source: Federal Reserve, 2023', 'According to a 2024 analysis by the Federal Reserve, rates rose.', false],
  ['Source: Federal Reserve, 2023', 'According to the Federal Reserve, rates rose.', false],
  ['Source: IMF, 2023', 'According to the IMF in twenty twenty-three, rates rose.', true],
  ['Source: Smith', 'The Smithsonian reviewed the data.', false],
  ['Source: Bank World', 'According to the World Bank, rates rose.', false],
  ['Source: it', 'It was reported.', false],
  ['Source: a study', 'According to a study, rates rose.', false],
  ['Source: Instituto Nacional de Estadística', 'Según el Instituto Nacional de Estadística, subió.', true],
  ['Source: 1000 Genomes Project', 'According to the 1000 Genomes Project, this was observed.', true],
  ['Source: 1000 Genomes Project', 'The 2000 Genomes Project surveyed 1000 people.', false],
  ['Source: 2020 Ventures', 'The 2020 Ventures analysis reported a rise.', true],
  ['Source: 2020 Ventures', 'The Other Ventures analysis reported a rise in 2020.', false],
  ['Source: 23andMe', 'According to 23andMe, the rate increased.', true],
  ['Source: 23andMe', 'According to 24andMe, the rate increased.', false],
  ['Source: 350.org', 'According to 350.org, this was observed.', true],
  ['Source: 350.org', 'According to 360.org, this was observed.', false],
  ['Source: World the Bank', 'The World Bank reported an increase.', false],
  ['Source: The Society for the Study of Evolution', 'The Society for the Study of Evolution reported a change.', true],
  ['Source: The The', 'The result came from the researchers.', false],
  ['Source: Source Global', 'According to Source Global, output increased.', true],
  ['Source Global', 'According to Source Global, output increased.', true],
  ['Source Global', 'Global output increased.', false],
  ['Source: IMF (2023)', 'According to the IMF in twenty twenty-three, rates rose.', true],
  ['Source: IMF (2023)', 'According to the IMF in 2024, rates rose.', false],
  ['Source: 1000 Genomes Project, 2023', 'According to the 1000 Genomes Project in 2023, this was observed.', true],
  ['Source: 1000 Genomes Project, 2023', 'The 2000 Genomes Project surveyed 1000 people in 2023.', false],
];
for (const [citation, sentence, expected] of cases) assert.equal(sourceCitationOccurs(citation, sentence), expected, `${citation} / ${sentence}`);
console.log(`SOURCE CITATION PASS — ${cases.length} exact institution, acronym, year and boundary cases`);
