import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const read = (path: string) => readFileSync(join(process.cwd(), path), "utf8");
const schema = read("convex/schema.ts");
const convex = read("convex/youtubeThumbnailReplacements.ts");
const route = read("src/app/api/thumbnail-refresh/accept/route.ts");
const task = read("src/trigger/youtubeThumbnailReplacement.ts");
const panel = read("src/components/ThumbnailRefreshInventoryPanel.tsx");
const automaticCore = read("src/trigger/automaticThumbnailReplacementCore.ts");
const candidateTask = read("src/trigger/thumbnailRefreshCandidate.ts");
const migrationTask = read("src/trigger/migrateYoutubeConnectorStorage.ts");
const youtubeAuth = read("convex/youtubeAuth.ts");

assert.match(schema, /youtubeThumbnailReplacements: defineTable/);
assert.match(schema, /candidateArtifactSha256: v\.string\(\)/);
assert.match(schema, /by_owner_candidate/);
assert.match(convex, /candidate\.thumbnailRefreshSourceRunId !== source\._id/);
assert.match(convex, /assessment\.status !== "current_golden_candidate"/);
assert.match(convex, /candidateArtifactSha256: artifactSha256/);
assert.match(convex, /applicationReceiptFingerprint/);
assert.match(convex, /Retired legacy videos cannot receive replacement thumbnails/);
assert.match(route, /confirmYoutubeVideoId !== input\.youtubeVideoId/);
assert.match(route, /action: "youtube-thumbnail-replacement"/);
assert.match(route, /scope: "global"/);
assert.match(task, /candidateSha256 !== dispatch\.candidateArtifactSha256/);
assert.match(task, /video\.channelId !== dispatch\.expectedYoutubeChannelId/);
assert.match(task, /setVideoThumbnailWithAccessToken/);
assert.match(task, /completeApplication/);
assert.doesNotMatch(panel, />Use on YouTube</);
assert.doesNotMatch(panel, /Confirm video/);
assert.match(panel, /Automatic YouTube sync queued/);
assert.match(panel, /New Library thumbnail active/);
assert.match(automaticCore, /AUTOMATIC_THUMBNAIL_POLICY_ACTOR_PREFIX/);
assert.match(automaticCore, /youtubeThumbnailReplacementTriggerRequest/);
assert.match(candidateTask, /queueAutomaticThumbnailReplacement/);
assert.match(youtubeAuth, /export const migrateLegacyTokenStorage = mutation/);
assert.match(youtubeAuth, /refreshToken: undefined/);
assert.match(youtubeAuth, /row\.updatedAt !== args\.expectedUpdatedAt/);
const migrationSection = youtubeAuth.slice(youtubeAuth.indexOf("export const migrateLegacyTokenStorage"));
const migrationPatch = migrationSection.match(/await ctx\.db\.patch\(row\._id, \{([\s\S]*?)\n    \}\);/)?.[1] ?? "";
assert.ok(migrationPatch, "the storage migration must atomically patch the connector");
assert.doesNotMatch(migrationPatch, /tokenVersion:/, "storage migration must preserve the logical connector version");
assert.match(migrationTask, /decryptSecret\(refreshTokenCiphertext/);
assert.match(migrationTask, /migrateLegacyTokenStorage/);
assert.doesNotMatch(migrationTask, /console\.(?:log|error)/);
assert.match(convex, /resumed_after_storage_migration/);

console.log("YouTube thumbnail replacement wiring: PASS");
